LENGTH = 'Length'
HEIGHT = 'Height' 
ENGINE_SIZE='Engine size'
HORSEPOWER = 'Horsepower'
PRICE = 'Price'
CITY_MILES_PAIR_GALLON = 'City Miles/galon'

DATA_FIELDS = [LENGTH, HEIGHT, ENGINE_SIZE, HORSEPOWER, PRICE, CITY_MILES_PAIR_GALLON]

DATA_PAIRS = [[LENGTH, HEIGHT], [ENGINE_SIZE, HORSEPOWER], [PRICE, CITY_MILES_PAIR_GALLON]]